# Development Stage
FROM node:20-bookworm-slim as development

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

#Production stage
FROM caddy:2-alpine as production
COPY Caddyfile /etc/caddy/Caddyfile
COPY . .



